### ISSUE TITLE
StatusAction should handle Failed payment

### ISSUE THREAD

**Issue by Geolim4** [StudioWaaz/WaazAxeptaPlugin#1]
All in the title:

https://github.com/StudioWaaz/WaazAxeptaPlugin/blob/47605bb3121e2e57ffeddc10e7986a309289e26e/src/Action/StatusAction.php#L62

The StatusAction should also handle failed payments:
```php
        if ($status === PaymentInterface::STATE_FAILED) {

            $request->markFailed();

            return;
        }
```

**Comment by ehibes** [comment]
Hi @Geolim4,
I fixed it on last commit https://github.com/StudioWaaz/WaazAxeptaPlugin/commit/c10f8d390660d79f383bab17323d161769947541

**Comment by Geolim4** [comment]
Thank you @ehibes  !
