### ISSUE TITLE
\Waaz\AxeptaPlugin\Action\NotifyAction::execute should check if state machine CAN before apply

### ISSUE THREAD

**Issue by Geolim4** [StudioWaaz/WaazAxeptaPlugin#2]
In some rare case I got an exception returned to the PSP through the notification because the payment is unable to migrate to completed as it is already completed.:

This code:
```php    
$this->stateMachineFactory->get($payment, PaymentTransitions::GRAPH)->apply(PaymentTransitions::TRANSITION_COMPLETE);
```

Should migrate to:
```php
$sm = $this->stateMachineFactory->get($payment, PaymentTransitions::GRAPH);
if ($sm->(PaymentTransitions::TRANSITION_COMPLETE)) {
    $sm->apply(PaymentTransitions::TRANSITION_COMPLETE);
}
```

**Comment by ehibes** [comment]
Hi @Geolim4, It seems strage that the payment state is already completed... 
Can you make a PR of your code ? Thanks in advance.

**Comment by Geolim4** [comment]
> Hi @Geolim4, It seems strage that the payment state is already completed... Can you make a PR of your code ? Thanks in advance.

In fact, sometimes the PSP is sending the notification AFTER that the customer returned on the shop and the signed url query already transitioned the order to completed. So when the PSP send the notification: Error 500.

Then the PSP will retry each hours until it gives up after 3 retries.

I'll send you the PR by the end of week.
